#define NOERROR      0
#define WSFULLerr    1
#define SYNTAXerr    2
#define INDEXerr     3
#define RANKerr      4
#define LENGTHerr    5
#define VALUEerr     6
#define FORMATerr    7
#define RESULTerr    8
#define DOMAINerr   11
#define NONCEerr    16
#define FTIEerr     18
#define FACCESerr   19
#define FINDEXerr   20
#define FFULLerr    21
#define FNAMEerr    22
#define FDAMAGerr   23
#define FTIEDerr    24
#define FSYSHWerr   25
#define FSYSTMerr   26
#define FSYSNAerr   28
#define FLIBNAerr   29
#define FSYSTUerr   30
#define FTQOTAerr   31
#define FQOTAerr    32
#define FRESRVerr   33
#define NOSPACerr   34
#define FCDAMGerr   38
#define WSLCKDerr   45
#define WSNFNDerr   46
#define WSNREDerr   47
#define SYSTEMerr   68
#define IQTAEXerr   72
#define NOSHARerr   73
#define ICAPEXerr   74
#define SHTABFerr   75
#define PRTABFerr   76
#define IDINUSerr   77
#define QPPerr      78
#define QPWerr      79
#define QIOerr      80
#define QRLerr      81
#define QCTerr      82
#define QHTerr      83
#define QPSerr      84
#define QFCerr      85
#define STOPerr   1001
#define ATTNerr   1002
#define INTerr    1003
#define INPINTerr 1004
#define SHVINTerr 1005
#define FILINTerr 1006
#define FBKINTerr 1007

