OBJS = clr.o d.o df.o dt.o k.o m.o ma.o n.o p.o p0.o s.o u.o e.o th.o \
	dth.o fd.o ind.o m1.o t.o m2.o m3.o thenc.o q1.o pk.o c.o q0.o \
	fmt.o fmtp.o rs.o o.o uc.o mf.o unixos.o st.o sv.o i.o cq.o cqu.o

CFLAGS = -g -c -Idefs -Iext -Iqtmps

INC_D = defs aplerrno.h

INC_E = ext defs aplerrno.h

INC_F = ext defs aplerrno.h qtmps filestructs.h

apl : $(OBJS)
	clang -o apl $(OBJS)

clr.o : clr.c $(INC_E) qtmps
	clang $(CFLAGS) clr.c

d.o : d.c $(INC_D)
	clang $(CFLAGS) d.c

df.o : df.c $(INC_E)
	clang $(CFLAGS) df.c

k.o : k.c $(INC_E)
	clang $(CFLAGS) k.c

dt.o : dt.c $(INC_D)
	clang $(CFLAGS) dt.c
                                                                                                  
m.o : m.c $(INC_E)
	clang $(CFLAGS) m.c

ma.o : ma.c $(INC_E) qtmps
	clang $(CFLAGS) ma.c
       
n.o : n.c $(INC_E) qtmps
	clang $(CFLAGS) n.c

p.o : p.c $(INC_E) qtmps
	clang $(CFLAGS) p.c

p0.o : p0.c $(INC_E)
	clang $(CFLAGS) p0.c

e.o : e.c $(INC_E) qtmps
	clang $(CFLAGS) e.c

pk.o : pk.c $(INC_E) qtmps
	clang $(CFLAGS) pk.c

fmt.o : fmt.c $(INC_E)
	clang $(CFLAGS) fmt.c

fmtp.o : fmtp.c $(INC_E)
	clang $(CFLAGS) fmtp.c

o.o : o.c $(INC_E) qtmps
	clang $(CFLAGS) o.c

uc.o : uc.c $(INC_E)
	clang $(CFLAGS) uc.c

mf.o : mf.c $(INC_E)
	clang $(CFLAGS) mf.c

unixos.o : unixos.c $(INC_E)
	clang $(CFLAGS) unixos.c

st.o : st.c $(INC_E)
	clang $(CFLAGS) st.c

sv.o : sv.c $(INC_E)
	clang $(CFLAGS) sv.c

u.o : u.c $(INC_E) qtmps
	clang $(CFLAGS) u.c

s.o : s.c $(INC_E) qtmps
	clang $(CFLAGS) s.c

th.o : th.c $(INC_E) qtmps
	clang $(CFLAGS) th.c

dth.o : dth.c $(INC_E)
	clang $(CFLAGS) dth.c

fd.o : fd.c $(INC_E) qtmps
	clang $(CFLAGS) fd.c

ind.o : ind.c $(INC_E)
	clang $(CFLAGS) ind.c

m1.o : m1.c $(INC_E)
	clang $(CFLAGS) m1.c

t.o : t.c $(INC_E) qtmps
	clang $(CFLAGS) t.c

m2.o : m2.c $(INC_E)
	clang $(CFLAGS) m2.c

m3.o : m3.c $(INC_E) qtmps
	clang $(CFLAGS) m3.c

thenc.o : thenc.c $(INC_E) qtmps
	clang $(CFLAGS) thenc.c

q1.o : q1.c $(INC_E) qtmps
	clang $(CFLAGS) q1.c

c.o : c.c $(INC_E) qtmps
	clang $(CFLAGS) c.c

q0.o : q0.c $(INC_E)
	clang $(CFLAGS) q0.c

rs.o : rs.c $(INC_E) qtmps
	clang $(CFLAGS) rs.c

i.o : i.c $(INC_E) qtmps
	clang $(CFLAGS) i.c

cq.o : cq.c $(INC_E) qtmps
	clang $(CFLAGS) cq.c

cqu.o : cqu.c $(INC_E) qtmps
	clang $(CFLAGS) cqu.c


